title: MD ARIFUL HAQUE
author: MD ARIFUL HAQUE
email: mah.shamim@gmail.com
description: only for test

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  mah-shamim

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
